#
# # 
# Copyright (C) 2025 Iheb Chagra
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# 
#

BACTERIA_LIST = [
    "Achromobacter xylosoxidans",
    "Acinetobacter baumannii",
    "Acinetobacter pittii",
    "Actinobacillus pleuropneumoniae",
    "Actinomyces israelii",
    "Actinomyces spp",
    "Aerococcus sanguinicola",
    "Aerococcus urinae",
    "Aeromonas caviae",
    "Aeromonas hydrophila",
    "Aeromonas veronii",
    "Alcaligenes faecalis",
    "Alcaligenes xylosoxidans",
    "Aliarcobacter butzleri",
    "Aliarcobacter cryaerophilus",
    "Aliarcobacter lanthieri",
    "Anaerobic cocci Gram positive",
    "Anaerococcus prevotii",
    "Anaerococcus prevotii (P. prevotii)",
    "Arcanobacterium pyogenes",
    "Aspergillus flavus Etest",
    "Aspergillus flavus EUCAST",
    "Aspergillus fumigatus Etest",
    "Aspergillus fumigatus EUCAST",
    "Aspergillus nidulans Etest",
    "Aspergillus nidulans EUCAST",
    "Aspergillus niger Etest",
    "Aspergillus niger EUCAST",
    "Aspergillus spp EUCAST",
    "Aspergillus sydowii EUCAST",
    "Aspergillus terreus Etest",
    "Aspergillus terreus EUCAST",
    "Aspergillus versicolor Etest",
    "Aspergillus versicolor EUCAST",
    "Bacillus anthracis",
    "Bacillus cereus",
    "Bacillus subtilis",
    "Bacteroides (Phocaeicola) vulgatus",
    "Bacteroides caccae",
    "Bacteroides capillosus",
    "Bacteroides eggerthii",
    "Bacteroides fragilis",
    "Bacteroides fragilis ATCC 25285",
    "Bacteroides fragilis group",
    "Bacteroides gracilis",
    "Bacteroides massiliensis",
    "Bacteroides nordii",
    "Bacteroides ovatus",
    "Bacteroides salyersae",
    "Bacteroides splanchnicus",
    "Bacteroides stercoralis",
    "Bacteroides thetaiotaomicron",
    "Bacteroides uniformis",
    "Bacteroides ureolyticus",
    "Bifidobacterium adolescentis",
    "Bifidobacterium angulatum",
    "Bifidobacterium animalis",
    "Bifidobacterium bifidum",
    "Bifidobacterium breve",
    "Bifidobacterium catenulatum",
    "Bifidobacterium dentium",
    "Bifidobacterium longum",
    "Bifidobacterium pseudocatenulatum",
    "Bifidobacterium pseudolongum",
    "Bifidobacterium ruminantium",
    "Bifidobacterium thermophilum",
    "Bilophila wadsworthia",
    "Bordetella bronchiseptica",
    "Bordetella pertussis",
    "Brucella melitensis",
    "Burkholderia cepacia complex",
    "Burkholderia pseudomallei",
    "Campylobacter coli",
    "Campylobacter fetus",
    "Campylobacter hyointestinalis",
    "Campylobacter jejuni",
    "Campylobacter jejuni ATCC 33560",
    "Campylobacter lari",
    "Campylobacter upsaliensis",
    "Candida albicans EUCAST",
    "Candida auris EUCAST",
    "Candida ciferrii EUCAST",
    "Candida dubliniensis EUCAST",
    "Candida famata EUCAST",
    "Candida fermentati EUCAST",
    "Candida glabrata EUCAST",
    "Candida guilliermondii EUCAST",
    "Candida hellenica EUCAST",
    "Candida holmii EUCAST",
    "Candida inconspicua EUCAST",
    "Candida intermedia EUCAST",
    "Candida kefyr EUCAST",
    "Candida krusei EUCAST",
    "Candida lambica EUCAST",
    "Candida lipolytica EUCAST",
    "Candida lusitaniae EUCAST",
    "Candida magnoliae EUCAST",
    "Candida nivariensis EUCAST",
    "Candida norvegensis DIN",
    "Candida norvegensis EUCAST",
    "Candida orthopsilosis EUCAST",
    "Candida palmioleophila EUCAST",
    "Candida parapsilosis EUCAST",
    "Candida pararugosa EUCAST",
    "Candida pelliculosa EUCAST",
    "Candida pintolopesii EUCAST",
    "Candida rugosa EUCAST",
    "Candida sake EUCAST",
    "Candida tropicalis EUCAST",
    "Candida utilis EUCAST",
    "Candida valida EUCAST",
    "Chlamydophila pneumoniae",
    "Chryseobacterium meningosepticum",
    "Chryseobacterium spp",
    "Citrobacter amalonaticus",
    "Citrobacter braakii",
    "Citrobacter diversus",
    "Citrobacter farmeri",
    "Citrobacter freundii",
    "Citrobacter koseri",
    "Citrobacter luteola",
    "Clostridioides difficile",
    "Clostridium butyricum",
    "Clostridium innocuum",
    "Clostridium perfringens",
    "Clostridium perfringens ATCC 13124",
    "Clostridium perfringens DSM 25589",
    "Clostridium septicum",
    "Clostridium sordelli",
    "Clostridium sporogenes",
    "Clostridium symbosium",
    "Corynebacterium afermentans",
    "Corynebacterium amycolatum",
    "Corynebacterium aurimucosum",
    "Corynebacterium diphtheriae",
    "Corynebacterium glucuronolyticum",
    "Corynebacterium jeikeium",
    "Corynebacterium macginleyi",
    "Corynebacterium propinquum",
    "Corynebacterium pseudodiphtheriticum",
    "Corynebacterium singulare",
    "Corynebacterium striatum",
    "Corynebacterium ulcerans",
    "Corynebacterium urealyticum",
    "Cronobacter sakazakii",
    "Cryptococcus gattii EUCAST",
    "Cryptococcus neoformans DIN",
    "Cryptococcus neoformans Etest",
    "Cryptococcus neoformans EUCAST",
    "Cryptococcus neoformans NCCLS",
    "Cryptococcus spp",
    "Cutibacterium acnes",
    "Eggerthella lenta",
    "Eikenella corrodens",
    "Enterobacter agglomerans",
    "Enterobacter amnigenus",
    "Enterobacter asburiae",
    "Enterobacter cancerogenus",
    "Enterobacter cloacae",
    "Enterobacter dissolvens",
    "Enterobacter gergoviae",
    "Enterobacter hormaechei",
    "Enterobacter intermedium",
    "Enterobacter kobei",
    "Enterobacter ludwigii",
    "Enterobacter sakazakii",
    "Enterobacter taylorae",
    "Enterocloster clostridioforme",
    "Enterococcus avium",
    "Enterococcus casseliflavus",
    "Enterococcus cecorum",
    "Enterococcus durans",
    "Enterococcus faecalis",
    "Enterococcus faecalis ATCC 29212",
    "Enterococcus faecalis ATCC 51299",
    "Enterococcus faecium",
    "Enterococcus gallinarum",
    "Enterococcus hirae",
    "Enterococcus lactis",
    "Enterococcus mundtii",
    "Enterococcus raffinosus",
    "Escherichia coli",
    "Escherichia coli ATCC 25922",
    "Escherichia coli ATCC 35218",
    "Escherichia coli NCTC 13846",
    "Finegoldia magna",
    "Francisella tularensis",
    "Fusarium (Gibberella) fujikuroi SC EUCAST",
    "Fusarium solani SC EUCAST",
    "Fusobacterium mortiferum",
    "Fusobacterium necrophorum",
    "Fusobacterium nucleatum",
    "Fusobacterium varium",
    "Haemophilus (Glaessarella) parasuis",
    "Haemophilus aphrophilus",
    "Haemophilus influenzae",
    "Haemophilus influenzae ATCC 49247",
    "Haemophilus influenzae ATCC 49766",
    "Haemophilus influenzae NCTC 8468",
    "Haemophilus parainfluenzae",
    "Hafnia alvei",
    "Helicobacter pylori",
    "Histophilus somni",
    "Kingella kingae",
    "Klebsiella aerogenes",
    "Klebsiella oxytoca",
    "Klebsiella ozaenae",
    "Klebsiella pneumoniae",
    "Klebsiella pneumoniae ATCC 700603",
    "Klebsiella terrigena",
    "Klebsiella variicola",
    "Kocuria kristinae",
    "Kodamaea ohmeri EUCAST",
    "Lactobacillus acidophilus",
    "Lactobacillus amylovorus",
    "Lactobacillus animalis",
    "Lactobacillus brevis",
    "Lactobacillus buchneri",
    "Lactobacillus casei",
    "Lactobacillus crispatus",
    "Lactobacillus curvatus",
    "Lactobacillus delbrueckii",
    "Lactobacillus fermentum",
    "Lactobacillus gallinarum",
    "Lactobacillus gasseri",
    "Lactobacillus helveticus",
    "Lactobacillus johnsonii",
    "Lactobacillus lactis",
    "Lactobacillus paracasei",
    "Lactobacillus paraplantarum",
    "Lactobacillus pentosus",
    "Lactobacillus plantarum",
    "Lactobacillus reuteri",
    "Lactobacillus rhamnosus",
    "Lactobacillus sakei",
    "Lactobacillus salivarius",
    "Lactobacillus spp",
    "Lactococcus lactis",
    "Legionella pneumophila",
    "Listeria monocytogenes",
    "Mannheimia haemolytica",
    "Moraxella catarrhalis",
    "Morganella morganii",
    "Mycobacterium abscessus",
    "Mycobacterium avium",
    "Mycobacterium avium ATCC 700898",
    "Mycobacterium intracellulare",
    "Mycobacterium marinum",
    "Mycobacterium peregrinum ATCC 700686",
    "Mycobacterium tuberculosis",
    "Mycobacterium tuberculosis ATCC 27294",
    "Mycoplasma bovis",
    "Mycoplasma hyopneumoniae",
    "Mycoplasma pneumoniae",
    "Neisseria gonorrhoeae",
    "Neisseria meningitidis",
    "Nocardia aboflava",
    "Nocardia abscessus",
    "Nocardia aobensis",
    "Nocardia asiatica",
    "Nocardia asteroides",
    "Nocardia brasiliensis",
    "Nocardia carnea",
    "Nocardia cyriacigeorgica",
    "Nocardia farcinica",
    "Nocardia flavorosea",
    "Nocardia ignorata",
    "Nocardia niigatensis",
    "Nocardia nova",
    "Nocardia otitidiscaviarum",
    "Nocardia pseudobrasiliensis",
    "Nocardia rhamnosiphila",
    "Nocardia shimofusensis",
    "Nocardia sienata",
    "Nocardia spp",
    "Nocardia takedensis",
    "Nocardia transvalensis",
    "Nocardia veterana",
    "Nocarida asiatica",
    "Pantoea agglomerans",
    "Parabacteroides distasonis",
    "Parabacteroides goldsteinii",
    "Parabacteroides merdae",
    "Parabacteroides merdae (B. merdae)",
    "Parvimonas micra",
    "Pasteurella aerogenes",
    "Pasteurella canis",
    "Pasteurella dagmatis",
    "Pasteurella multocida",
    "Pasteurella stomatis",
    "Pediococcus acidilactici",
    "Pediococcus pentosaceus",
    "Peptoniphilus harei",
    "Peptostreptococcus anaerobius",
    "Peptostreptococcus asacchoralyticus",
    "Pichia anomala EUCAST",
    "Plesiomonas shigelloides",
    "Porphyromonas asaccharolytica",
    "Prevotella bivia",
    "Prevotella buccae",
    "Prevotella corporis",
    "Prevotella denticola",
    "Prevotella disiens",
    "Prevotella heparinolytica",
    "Prevotella intermedia",
    "Prevotella loeschei",
    "Prevotella melaninogenica",
    "Prevotella nanceiensis",
    "Prevotella oralis",
    "Prevotella spp beta lactamase neg",
    "Prevotella spp beta lactamase pos",
    "Proteus mirabilis",
    "Proteus penneri",
    "Proteus vulgaris",
    "Providencia rettgeri",
    "Providencia stuartii",
    "Pseudoglutamicibacter cumminsii",
    "Pseudomonas aeruginosa",
    "Pseudomonas aeruginosa ATCC 27853",
    "Pseudomonas fluorescens group",
    "Pseudomonas putida group",
    "Pseudomonas spp (non-aeruginosa)",
    "Pseudomonas stutzeri group",
    "Raoultella ornithinolytica",
    "Raoultella planticola",
    "Rhodotorula mucilaginosa EUCAST",
    "Rothia aeria",
    "Rothia amarae",
    "Rothia dentocariosa",
    "Rothia mucilaginosa",
    "Rothia nasimurium",
    "Rothia terrae",
    "Saccharomyces cerevisiae EUCAST",
    "Salmonella agona",
    "Salmonella anatum",
    "Salmonella bareilly",
    "Salmonella berta",
    "Salmonella braenderup",
    "Salmonella derby",
    "Salmonella Dublin",
    "Salmonella enterica",
    "Salmonella Enteritidis",
    "Salmonella Group B",
    "Salmonella Group C",
    "Salmonella Group D",
    "Salmonella hadar",
    "Salmonella hartford",
    "Salmonella heidelberg",
    "Salmonella infantis",
    "Salmonella javiana",
    "Salmonella litchfield",
    "Salmonella manhattan",
    "Salmonella mbandaka",
    "Salmonella mississippi",
    "Salmonella montevideo",
    "Salmonella muenchen",
    "Salmonella newport",
    "Salmonella oranienburg",
    "Salmonella panama",
    "Salmonella Paratyphi",
    "Salmonella poona",
    "Salmonella rubislaw",
    "Salmonella saintpaul",
    "Salmonella sandiego",
    "Salmonella schwarzengrund",
    "Salmonella senftenberg",
    "Salmonella spp",
    "Salmonella stanley",
    "Salmonella thompson",
    "Salmonella Typhi",
    "Salmonella Typhimurium",
    "Salmonella virchow",
    "Serratia ficaria",
    "Serratia fonticola",
    "Serratia grimesii",
    "Serratia liquefaciens",
    "Serratia marcescens",
    "Serratia odorifera",
    "Serratia plymuthica",
    "Serratia rubidaea",
    "Serratia ureilytica",
    "Shigella boydii",
    "Shigella dysenteriae",
    "Shigella flexneri",
    "Shigella sonnei",
    "Shigella spp",
    "Staphylococcus argenteus",
    "Staphylococcus aureus",
    "Staphylococcus aureus ATCC 25923",
    "Staphylococcus aureus ATCC 29213",
    "Staphylococcus aureus MRSA",
    "Staphylococcus aureus MSSA",
    "Staphylococcus aureus NCTC 12493",
    "Staphylococcus auricularis",
    "Staphylococcus capitis",
    "Staphylococcus caprae",
    "Staphylococcus coagulase negative",
    "Staphylococcus coagulase negative MRSE",
    "Staphylococcus cohnii",
    "Staphylococcus epidermidis",
    "Staphylococcus epidermidis MRSE",
    "Staphylococcus epidermidis MSSE",
    "Staphylococcus felis",
    "Staphylococcus haemolyticus",
    "Staphylococcus hominis",
    "Staphylococcus hyicus",
    "Staphylococcus intermedius",
    "Staphylococcus kloosii",
    "Staphylococcus lugdunensis",
    "Staphylococcus pasteuri",
    "Staphylococcus pettenkoferi",
    "Staphylococcus pseudintermedius",
    "Staphylococcus saccharolyticus",
    "Staphylococcus saprophyticus",
    "Staphylococcus schleiferi",
    "Staphylococcus sciuri",
    "Staphylococcus simulans",
    "Staphylococcus warneri",
    "Staphylococcus xylosus",
    "Stenotrophomonas maltophilia",
    "Streptococcus acidominimus",
    "Streptococcus agalactiae",
    "Streptococcus anginosus",
    "Streptococcus anginosus group",
    "Streptococcus australis",
    "Streptococcus bovis",
    "Streptococcus bovis equinus group",
    "Streptococcus canis",
    "Streptococcus constellatus",
    "Streptococcus cristatus",
    "Streptococcus dysgalactiae",
    "Streptococcus equi subspecies equi",
    "Streptococcus equi subspecies zooepidemicus",
    "Streptococcus equisimilis",
    "Streptococcus gallolyticus",
    "Streptococcus gordonii",
    "Streptococcus group C",
    "Streptococcus group G",
    "Streptococcus infantarius",
    "Streptococcus infantis",
    "Streptococcus intermedius",
    "Streptococcus lutetiensis",
    "Streptococcus massiliensis",
    "Streptococcus mitis",
    "Streptococcus mitis group",
    "Streptococcus mutans",
    "Streptococcus mutans group",
    "Streptococcus oralis",
    "Streptococcus parasanguinis",
    "Streptococcus pasteurianus",
    "Streptococcus peroris",
    "Streptococcus pneumoniae",
    "Streptococcus pneumoniae ATCC 49619",
    "Streptococcus pseudopneumoniae",
    "Streptococcus pyogenes",
    "Streptococcus pyogenes CCUG 25571",
    "Streptococcus salivarius",
    "Streptococcus salivarius group",
    "Streptococcus sanguinis",
    "Streptococcus sanguinis group",
    "Streptococcus suis",
    "Streptococcus thermophilus",
    "Streptococcus uberis",
    "Streptococcus vestibularis",
    "Thomasclavelia ramosa (Cl. ramosa)",
    "Veillonella parvula",
    "Vibrio alginolyticus",
    "Vibrio cholerae",
    "Vibrio fluvialis",
    "Vibrio parahaemolyticus",
    "Vibrio vulnificus",
    "Weissella confusa",
    "Weissella viridescens",
    "Yersinia enterocolitica"
]


